### ISSUE TITLE
Use a structured file as source of truth, and generate markdown table from it

### ISSUE THREAD

**Issue by jin** [bazelbuild/proposals#5]
It's starting to get unwieldy to add or modify the table contents. @petroseskinder suggested that we can store the files in a YAML file, and generate the table using a script.

**Comment by jin** [comment]
cc @laurentlb

**Comment by laurentlb** [comment]
Later, the script can check that the information (e.g. doc status) matches with the documents written in markdown.

Any simple way to do that, without requiring everyone to run a script locally?

**Comment by jin** [comment]
Looks like there's the Checks API has been integrated into the PR flow: https://github.com/bazelbuild/proposals/pull/6/checks

**Comment by jin** [comment]
Not planning to do this. This repo doesn't change too often for increased complexity.
